### PR TITLE
feat: updating default values

### LINKED ISSUE #44: updating default values?
Hello Elone,

I have a situation where I am submitting the form and then want to continue using it with the submitted values set as the new default values. I need a way to update the defaults. Is that possible currently?

flow:
default values -> useForm -> change form values -> submit -> on success updated values are set as defaults

### PR DESCRIPTION
**Pull request by elonehoo**
fixed #44

### CODE REVIEW

**Comment by kylegl** [comment]
Works well, nice job. I added an option to make the default value update optional, off by default. Unless you think it should always do that.

Side note - I tried to use the 'reset' function returned from useForm and I got an error.

`TypeError: 'set' on proxy: trap returned falsish for property 'isDirty'`

Should probably address on a different branch but wanted to mention it.

**Comment by elonehoo** [comment]
I've found this problem, and I think it's time for us to refactor the library.

**Comment by kylegl** [comment]
Strange because i know it worked before. Ok let me know how you want to proceed.

**Review by kylegl — APPROVED** [review]

**Comment by elonehoo** [comment]
Looks like I found the problem. Let me work on it.

**Comment by elonehoo** [comment]
That should do it.

**Comment by elonehoo** [comment]
I'm going to be 9-to-9er.

**Comment by kylegl** [comment]
nice work! looks good to me

**Comment by elonehoo** [comment]
If you think it's okay, merge it in

**Comment by elonehoo** [comment]
Better give me your npm name, I think I can give you access to npm packages

**Comment by kylegl** [comment]
@kylegl

**Comment by kylegl** [comment]
Thanks got it.

**Comment by elonehoo** [comment]
It was so much fun coding with you!

**Comment by kylegl** [comment]
Well you did most of it but same. This module is 🔥

**Pull request merged**
